### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by DzunN86** [DzunN86/hoobank-landingpage#16]

**Comment by aryamankha** [comment]
Happy to make the nav bar sticky! Feel free to assign this to me

**Comment by DzunN86** [comment]
> Happy to make the nav bar sticky! Feel free to assign this to me

the expectation is like the [tailwind css navbars](https://tailwindcss.com/) it has blur background when it's scrolled

**Comment by SuNak27** [comment]
assign to me
